[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_new = "35HDSd9N8WhJfW71ASY9Zgaagom32vLvxemDriySDCtj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
